spring:
  profiles.active: default

---
spring:
  profiles: default

spring.data.mongodb:
  host: localhost
  port: 27017

spring.thymeleaf:
    cache: false

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/toboot
  username: postgres
  password: password

management:
  port: 8081
  contextPath: /manage
  security:
    enabled: false

---
spring:
   profiles: heroku

spring.thymeleaf:
  cache: true
