spring:
  profiles.active: default
---
spring:
  profiles: default

spring.thymeleaf:
    cache: false

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/toboot
  username: postgres
  password: password

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      repositories:
        enabled : false

management:
  port: 8081
  contextPath: /manage
  security:
    enabled: false
---
spring:
   profiles: heroku

spring.thymeleaf:
  cache: true
